(part "ISL9V5036P3-F085"
    (packageRef "TO254P470X1016X2019-3P")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "C") (portType INOUT))
        (port "3" (symbPinId 3) (portName "E") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "ISL9V5036P3-F085")
    (property "Mouser_Part_Number" "512-ISL9V5036P3-F085")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi-Fairchild/ISL9V5036P3-F085?qs=0lQeLiL1qyZrd8MAKfN5lQ%3D%3D")
    (property "Arrow_Part_Number" "ISL9V5036P3-F085")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/isl9v5036p3-f085/on-semiconductor?utm_currency=USD&region=nac")
    (property "Description" "Logic Level Gate Drive; Industry Standard TO-220 package; SCIS Energy = 500mJ at TJ = 25; Qualified to AEC Q101; RoHS Compliant")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/ISL9V5036S3ST-D.PDF")
    (property "symbolName1" "ISL9V5036P3-F085")
)
