(part "ATTINY85-20PU"
    (packageRef "DIP781W56P254L950H533Q8N")
    (interface
        (port "1" (symbPinId 1) (portName "PB5_(PCINT5/%RESET%/ADC0/DW)") (portType INOUT))
        (port "2" (symbPinId 2) (portName "PB3_(PCINT3/XTAL1/CLKI/%OC1B%/ADC3)") (portType INOUT))
        (port "3" (symbPinId 3) (portName "PB4_(PCINT4/XTAL2/CLKO/OC1B/ADC2)") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GROUND") (portType GROUND))
        (port "5" (symbPinId 5) (portName "PB0_(MOSI/DI/SDA/AIN0/OC0A/OC1A/AREF/PCINT0)") (portType INOUT))
        (port "6" (symbPinId 6) (portName "PB1_(MISO/DO/AIN1/OC0B/OC1A/PCINT1)") (portType INOUT))
        (port "7" (symbPinId 7) (portName "PB2_(SCK/USCK/SCL/ADC1/T0/INT0/PCINT2)") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCC") (portType POWER))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "ATTINY85-20PU")
    (property "Mouser_Part_Number" "556-ATTINY85-20PU")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology/ATTINY85-20PU?qs=8jWQYweyg6NCiiaOb5GI9Q%3D%3D")
    (property "Arrow_Part_Number" "ATTINY85-20PU")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/attiny85-20pu/microchip-technology?utm_currency=USD&region=nac")
    (property "Description" "MICROCHIP - ATTINY85-20PU - MICROCONTROLLER MCU, 8 BIT, ATTINY, 20MHZ, DIP-8")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/ATTINY85-20PU.pdf")
    (property "symbolName1" "ATTINY85-20PU")
)
