(part "BC547"
    (packageRef "BC547")
    (interface
        (port "1" (symbPinId 1) (portName "C") (portType INOUT))
        (port "2" (symbPinId 2) (portName "B") (portType INOUT))
        (port "3" (symbPinId 3) (portName "E") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Rochester Electronics")
    (property "Manufacturer_Part_Number" "BC547")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "NPN Epitaxial Silicon Transistor, To-92, 100mA, 6V")
    (property "Datasheet_Link" "")
    (property "symbolName1" "BC547")
)
