(part "PC817X2NSZ9F"
    (packageRef "DIP762W60P254L460H450Q4N")
    (interface
        (port "1" (symbPinId 1) (portName "ANODE") (portType INOUT))
        (port "2" (symbPinId 2) (portName "CATHODE") (portType INOUT))
        (port "3" (symbPinId 3) (portName "EMITTER") (portType INOUT))
        (port "4" (symbPinId 4) (portName "COLLECTOR") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Sharp Microelectronics")
    (property "Manufacturer_Part_Number" "PC817X2NSZ9F")
    (property "Mouser_Part_Number" "852-PC817X2NSZ9F")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Sharp-Microelectronics/PC817X2NSZ9F?qs=rrS6PyfT74ehABo1g8zXHw%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Transistor Output Optocouplers Photocoupler")
    (property "Datasheet_Link" "http://www.socle-tech.com/doc/IC%20Channel%20Product/Optoelectronic%20Components/Photocoupler/PC817X_NSZ9FSeries_SPEC.pdf")
    (property "symbolName1" "PC817X2NSZ9F")
)
