(part "IRF4905"
    (packageRef "TO254P469X1042X1967-3P")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "D") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "IRF4905")
    (property "Mouser_Part_Number" "N/A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Infineon-IR/IRF4905?qs=zO0nedAqnNIhlaIbSqqpvQ%3D%3D")
    (property "Arrow_Part_Number" "IRF4905")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/irf4905/international-rectifier?region=nac")
    (property "Description" "MOSFET Transistor, P-Channel, TO-220AB")
    (property "Datasheet_Link" "https://www.infineon.com/dgdl/irf4905pbf.pdf?fileId=5546d462533600a4015355e329b1197e")
    (property "symbolName1" "IRF4905")
)
