(part "KA78M05RTM"
    (packageRef "KA78M05RTM")
    (interface
        (port "1" (symbPinId 1) (portName "INPUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "OUTPUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "KA78M05RTM")
    (property "Mouser_Part_Number" "512-KA78M05RTM")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi-Fairchild/KA78M05RTM?qs=SpPkH8nd0tby1gymq1mGIg%3D%3D")
    (property "Arrow_Part_Number" "KA78M05RTM")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ka78m05rtm/on-semiconductor")
    (property "Description" "IC REG LINEAR 5V 500MA DPAK")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/KA78M05RTM.pdf")
    (property "symbolName1" "KA78M05RTM")
)
